/**
 * Pokemon Powers API
 * Add your description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A LongDataItem
 */
export interface LongDataItem { 
    /**
     * The text of the item
     */
    text?: string;
    /**
     * The index of the item
     */
    index?: number;
}

