/**
 * Pokemon Powers API
 * Add your description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * LongData
 */
export interface LongData { 
    /**
     * The index of the data item
     */
    index?: number;
    /**
     * The data item
     */
    item?: string;
}

