/**
 * Pokemon Powers API
 * Add your description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PokemonHeight
 */
export interface PokemonHeight { 
    /**
     * The height of the Pokemon
     */
    height?: string;
}

