/**
 * Pokemon Powers API
 * Add your description
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PokemonColor
 */
export interface PokemonColor { 
    /**
     * The color of the Pokemon
     */
    color?: string;
}

